Refact call evaluator and add operator
alex-lairan/rpn-skeleton pull request #2
Opened 2019-05-20 12:08 UTC by brumax27

2019-05-20 16:37 UTC, alex-lairan requested changes

2019-05-20 16:37 UTC, alex-lairan commented on src/main/java/rpn/Absolute.java
> +        super(stack.pop(),null);
I don't think this is relevant.

What if ternary elements ?

2019-05-21 17:55 UTC, alex-lairan commented
Je suis perdu pour le Drop et le Swap.

Je pense que l'on peux return un `array` dans process, mais il faudrais le gerer dans chaque noeud, et ce serais horible.

Sans doute 2 fonction, une process interne, et un process externe.

2019-06-01 15:16 UTC, alex-lairan commented
J'ai reussi, je me suis pris la tete pour rien :grin:

2019-06-01 15:16 UTC, alex-lairan approved these changes

2019-06-01 15:18 UTC, brumax27 reviewed
i'm ok

2019-06-02 08:27 UTC, nntucao commented
it's ok for me, I have nothing to add or modify :)

2019-06-02 22:40 UTC, merged